[[plugins]]
package = "netlify-plugin-visual-diff"
  [plugins.inputs]
  external = ["node:events"]

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Ensure that devDependencies are installed.
  NPM_CONFIG_PRODUCTION = "false"

[context.production.environment]
  NODE_VERSION = "v22.11.0"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 8888
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-ses", "openai", "jose"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://netlify-scripts.netlify.app; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.unsplash.com https://*.supabase.co; connect-src 'self' https://*.supabase.co wss://*.supabase.co;"