import type { Database } from '../../lib/supabase/types';
export declare abstract class BaseService<T extends keyof Database['public']['Tables']> {
    protected readonly table: T;
    constructor(table: T);
    protected get tableRef(): import("@supabase/postgrest-js").PostgrestQueryBuilder<Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T], T, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] extends infer T_1 ? T_1 extends (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] ? T_1 extends {
        Relationships: infer R;
    } ? R : unknown : never : never>;
    getAll(): Promise<import("@supabase/postgrest-js").UnstableGetResult<Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T]["Row"], T, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] extends infer T_1 ? T_1 extends (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] ? T_1 extends {
        Relationships: infer R;
    } ? R : unknown : never : never, "*">[]>;
    getById(id: string): Promise<import("@supabase/postgrest-js").UnstableGetResult<Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T]["Row"], T, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] extends infer T_1 ? T_1 extends (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] ? T_1 extends {
        Relationships: infer R;
    } ? R : unknown : never : never, "*">>;
    create(data: Database['public']['Tables'][T]['Insert']): Promise<import("@supabase/postgrest-js").UnstableGetResult<Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T]["Row"], T, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] extends infer T_1 ? T_1 extends (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] ? T_1 extends {
        Relationships: infer R;
    } ? R : unknown : never : never, "*">>;
    update(id: string, data: Database['public']['Tables'][T]['Update']): Promise<import("@supabase/postgrest-js").UnstableGetResult<Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T]["Row"], T, (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] extends infer T_1 ? T_1 extends (Database["public" extends keyof Database ? "public" : string & keyof Database] extends import("@supabase/postgrest-js/dist/cjs/types").GenericSchema ? Database["public" extends keyof Database ? "public" : string & keyof Database] : any)["Tables"][T] ? T_1 extends {
        Relationships: infer R;
    } ? R : unknown : never : never, "*">>;
    delete(id: string): Promise<void>;
}
